spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://52.194.73.44/ojackkyo?characterEncoding=utf-8
    password: kakao123
    username: root
    freemarker:
      content-type: application/json


server:
  port: 4000
