spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.17.102.131/ojackkyo?characterEncoding=utf-8
    password: 1234
    username: root
    freemarker:
      content-type: application/json


server:
  port: 4000
